### ISSUE TITLE
Empty list reaches unreachable!()

### ISSUE THREAD

**Issue by sbillig** [ethereum/fe#409] opened 2021-05-18 05:47 UTC
### What is wrong?

An empty list literal causes a panic in the analyzer.

### How can it be fixed

Not really sure what the best solution is. `expr_list` doesn't have enough information to return the correct type. We could maybe make the Array element type Optional, and fill it in when we know the expected type.

**Comment by cburgdorf** [comment] 2021-05-18 09:23
This is a duplicate of https://github.com/ethereum/fe/issues/256 which has a bit more info about how we might end up solving that. I have renamed the title of #256 to be more descriptive and will close this issue since the other one already has more info.

**Closed by cburgdorf** 2021-05-18 09:23 UTC
