### ISSUE TITLE
Plus Plus crash

### ISSUE THREAD

**Issue by edmiikk** [ethereum/fe#851] opened 2023-02-27 07:57 UTC
### What is wrong?
<shell>

$ RUST_BACKTRACE=full fe build src --overwrite

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TypeError(DiagnosticVoucher(PhantomData))', crates/analyzer/src/db/queries/module.rs:120:85
stack backtrace:
  58:     0x7fef13f53d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  59:     0x7fef13f53e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  60:     0x55b791b6e8be - <unknown>
  61:                0x0 - <unknown>
</shell>

### How can it be fixed

Change <code>passes++ ;</code>  -> <code>self.passes += 1 ;</code>

**Comment by edmiikk** [comment] 2023-02-27 08:15
Same error signature when parsing unexpected features:

```
     let last_error: String<"Error: Assertion Failed condition is false".length()> = "Error: Assertion Failed condition is false" ; 
```

**Comment by cburgdorf** [comment] 2023-02-27 08:46
Can you provide a small reproduction of the crash. Because the following doesn't crash but generate a proper user error:

```
contract Test {
    pub fn foo() {
        let x: u256 = 0
        x++
    }
}
```

**Comment by edmiikk** [comment] 2023-02-27 09:06
In main.fe the following code crashes fe:

```
pub struct log {
    pub text: String<100>
}

pub struct log_named_u256 {
    pub text: String<100>
    pub a256: u256
}

pub struct log_compare_u32 {
    pub text: String<100> ;
    pub expected_u32: u32 ;
    pub actual_u32: u32 ;
}

pub trait Failed {
    fn has_failed(mut self) ;
}

impl Failed for DSTest {
    fn has_failed(mut self) {
        if (self._failed) {
            revert 
        }
    }
}

pub struct DSTest {

    IS_TEST: bool;
    pub _failed: bool;
    pub passes: u32 ;
    pub failures: u32 ;

    pub fn new() -> DSTest {
        return DSTest(IS_TEST: true, _failed: false, passes: 0 , failures: 0) ;
    }
    
    
    pub fn failed(self) -> bool {
        return self._failed ;
    }
    
    
    fn _fail(mut self)  {
        //if (hasHEVMContext()) {
        //    (bool status, ) = HEVM_ADDRESS.call(
        //        abi.encodePacked(
        //            bytes4(keccak256("store(address,bytes32,bytes32)")),
        //            abi.encode(HEVM_ADDRESS, bytes32("failed"), bytes32(uint256(0x01)))
        //        )
        //    );
        //    status; // Silence compiler warnings
        //}
        self._failed = true;
        self.failures += 1 ;
    }
    
    
    //function assertTrue(bool condition) internal {
    //    if (!condition) {
    //        emit log("Error: Assertion Failed");
    //        fail();
    //    }
    //}
    
    pub fn assert_true(mut self, mut ctx: Context, truth: bool) {
        if (truth == false) {
            let last_error: String<100> = "Error: Assertion Failed condition is false" ;
            ctx.emit(log(text: last_error));
            self._fail();
        } else {
            self.passes += 1;
        }
    }
    
    pub fn assert_false(mut self, mut ctx: Context, untruth: bool) {
        if (untruth == true) {
            let last_error: String<100> = "Error: Assertion Failed condition is true" ;
            ctx.emit(log(text: last_error));
            self._fail();
        } else {
            self.passes += 1;
        }         
    }   
    
    pub fn assert_eq_u32(mut self, mut ctx: Context, expected_u32: u32, actual_u32: u32) {
        if (expected_u32 != actual_u32) {
            //let last_error: String<100> = "Error: Assertion Failed. " ;
            ctx.emit(log_compare_u32(text: "Error: Assertion Failed. ", expected_u32, actual_u32));
            self._fail();
        } else {
            passes++;
        } 
    } 
    
}

```

**Comment by cburgdorf** [comment] 2023-02-27 09:33
Thanks, I can confirm that this crashes in Fe `0.20.0` but it doesn't seem to crash on latest master so the bug should be fixed with the next released version.

**Closed by cburgdorf** 2023-02-27 09:33 UTC
Labels: type: bug

**Comment by edmiikk** [comment] 2023-02-27 10:10
Thanks Christoph.

**Comment by cburgdorf** [comment] 2023-02-27 10:27
Thanks for reporting!

**Comment by cburgdorf** [comment] 2023-03-01 09:50
@edmiikk Do you mind confirming if this appears to be fixed now with the latest release https://github.com/ethereum/fe/releases/tag/v0.21.0-alpha

**Comment by edmiikk** [comment] 2023-03-01 11:42
@cburgdorf. Yes all good:

<shell>
$ fe --version<br/>
fe 0.21.0-alpha
</shell>
<code>
self.passes ++ ;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  ^
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  unexpected token
</code>
