### ISSUE TITLE
Rust compiler interference

### ISSUE THREAD

**Issue by SHA888** [ethereum/fe#541] opened 2021-09-09 15:58 UTC
### Failed to compile guest_book.fe

I run the guest_book.fe contract:

> contract GuestBook:
>     messages: Map<address, String<100>>
> 
>     pub fn sign(self, book_msg: String<100>):
>         self.messages[msg.sender] = book_msg

and got an error: 

> ./fe_amd64 guest_book.fe 
> Unable to compile guest_book.fe.
> error: failed to parse function parameter
>   ┌─ guest_book.fe:4:21
>   │
> 4 │     pub fn sign(self, book_msg: String<100>):
>   │                     ^ Unexpected token. Expected `:`
>   │
>   = Note: parameter name must be followed by a colon and a type description
>   = Example: `self: u256`

 It seems the `./fe_amd64` is interfered by Rust compiler?

I use Ubuntu 20.04 + VS code with rust-analyzer extension.

**Comment by cburgdorf** [comment] 2021-09-09 16:24
Ah, so the problem is that our docs already show latest `master` (something that we need to fix mid term) which demands functions take `self` as the first parameter if their body somehow interacts with `self`. But the latest version of Fe which I assume you are on doesn't have that feature yet.

Sorry, the best answer that I can give you for now is to check out the docs at the latest tag which isn't as convenient as reading them from the website: https://github.com/ethereum/fe/tree/v0.8.0-alpha/docs/src

The code would look like this on the latest release:

``` 
contract GuestBook:
  messages: Map<address, String<100>>

  pub fn sign(book_msg: String<100>):
      self.messages[msg.sender] = book_msg

  pub fn get_msg(addr: address) -> String<100>:
      return self.messages[addr].to_mem()
```

Going to close this but feel free to ask if something remains unclear.

**Closed by cburgdorf** 2021-09-09 16:24 UTC

**Comment by cburgdorf** [comment] 2021-09-09 16:26
Btw, I quickly dumped this here so we don't forget to get to the version switcher in the docs eventually: https://github.com/ethereum/fe/issues/543

**Comment by SHA888** [comment] 2021-09-09 16:27
Thank you @cburgdorf :pray:
